export const FETCH_FAVORITE_DOGS = "FETCH_FAVORITE_DOGS";
export const FETCH_ERROR = "FETCH_ERROR";
export const LOADING_START = "LOADING_START";
export const ADD_FAVORITE_DOGS = "ADD_FAVORITE_DOGS";
export const REMOVE_FAVORITE_DOGS = "REMOVE_FAVORITE_DOGS";
export const DISABLE_BUTTON_BY_ID = "DISABLE_BUTTON_BY_ID";


